name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_DATABASE: batick
          MYSQL_USER: jimmyfish
          MYSQL_PASSWORD: nakedsexyteachers
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Migrate Database
      run: php artisan migrate --seed
    - name: Seeding Symbol
      run: php db:seed --class=SymbolSeeder
    - name: Run NPM
      run: npm install
    - name: Compiling Vite assets
      run: npm run build
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: batick
        DB_USERNAME: jimmyfish
        DB_PASSWORD: nakedsexyteachers
        BYBIT_BASE_URL: https://api.bytick.com
        BINANCE_BASE_URL: https://api.binance.com
      run: vendor/bin/phpunit
